server:
  port: 9191
  connection-timeout: 300000
spring :
  application :
    name : api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: ANSWERS-SERVICE
          uri: lb://ANSWERS-SERVICE
          predicates:
            - Path=/answers/**
          filters:
            - name: CircuitBreaker
              args:
                name: ANSWERS-SERVICE
                fallbackuri: forward:/answerFallback
        - id: QUESTIONS-SERVICE
          uri: lb://QUESTIONS-SERVICE
          predicates:
            - Path=/questions/**
          filters:
            - name: CircuitBreaker
              args:
                name: QUESTIONS-SERVICE
                fallbackuri: forward:/questionFallback
eureka:
  client:
    register-with-eureka : true
    fetch-registry: true
    serviceUrl:
      defaultZone : http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  instance:
    preferIpAddress: true
    hostname: eureka-0
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000