server:
  port: 8183
spring:
  profiles:
    active: house
  main:
    banner-mode: off
  application:
    name: answers-service
  zipkin:
    base-url: http://127.0.0.1:9411/

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

---
spring:
  profiles: house
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        show-sql: true

---
spring:
  profiles: office
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Mypassword
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        show-sql: true
---
spring:
  profiles: aws
  datasource:
    url: jdbc:mysql://demo.cun2agjqacir.ap-south-1.rds.amazonaws.com:3306/demo?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect